name: Web Api
env:
  AZURE_WEBAPP_NAME: ms-learn-api-management
  AZURE_WEBAPP_PACKAGE_PATH: "ms-learn-api-management/ms-learn-api-management.csproj"
  SOLUTION: "ms-learn-api-management/ms-learn-api-management.sln"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} --configuration Release

      - name: dotnet publish
        run: dotnet publish ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZURE_WEB_API_SECRET }}